name: ğŸ‡³ğŸ‡´ E2E Tests Â· Norway
permissions:
  contents: read
on:
  deployment_status:
    # only runs on successful deploy to main-site (Norway)
jobs:
  test:
    name: ğŸ§ª GiEffektivt (NO)
    if: github.event.deployment_status.state == 'success' && contains(github.event.deployment_status.target_url, 'main-site')
    uses: ./.github/workflows/e2e.yml
    with:
      group: "ğŸ‡³ğŸ‡´ GiEffektivt"
      base-url: ${{ github.event.deployment_status.target_url }}
      config-file: "cypress-no.config.ts"
    secrets: inherit
