name: ğŸ‡¸ğŸ‡ª E2E Tests Â· Sweden
permissions:
  contents: read
on:
  deployment_status:
    # only runs on successful deploy to ge-effektivt (Sweden)
jobs:
  test:
    name: ğŸ§ª GeEffektivt (SE)
    if: github.event.deployment_status.state == 'success' && contains(github.event.deployment_status.target_url, 'ge-effektivt')
    uses: ./.github/workflows/e2e.yml
    with:
      group: "ğŸ‡¸ğŸ‡ª GeEffektivt"
      base-url: ${{ github.event.deployment_status.target_url }}
      config-file: "cypress-se.config.ts"
    secrets: inherit
